"""
This type stub file was generated by pyright.
"""

def template_to_file(template_file, dest, output_encoding, **kw): # -> None:
    ...

def coerce_resource_to_filename(fname): # -> str:
    """Interpret a filename as either a filesystem location or as a package
    resource.

    Names that are non absolute paths and contain a colon
    are interpreted as resources and coerced to a file location.

    """
    ...

def pyc_file_from_path(path): # -> str | None:
    """Given a python source path, locate the .pyc."""
    ...

def edit(path): # -> None:
    """Given a source path, run the EDITOR for it"""
    ...

def load_python_file(dir_, filename): # -> ModuleType:
    """Load a file from the given path as a Python module."""
    ...

