"""
This type stub file was generated by pyright.
"""

from sqlalchemy import sql
from sqlalchemy.sql.expression import _BindParamClause

_vers = ...
sqla_13 = ...
sqla_14 = ...
AUTOINCREMENT_DEFAULT = ...
class _textual_index_element(sql.ColumnElement):
    """Wrap around a sqlalchemy text() construct in such a way that
    we appear like a column-oriented SQL expression to an Index
    construct.

    The issue here is that currently the Postgresql dialect, the biggest
    recipient of functional indexes, keys all the index expressions to
    the corresponding column expressions when rendering CREATE INDEX,
    so the Index we create here needs to have a .columns collection that
    is the same length as the .expressions collection.  Ultimately
    SQLAlchemy should support text() expressions in indexes.

    See SQLAlchemy issue 3174.

    """
    __visit_name__ = ...
    def __init__(self, table, text) -> None:
        ...
    
    def get_children(self): # -> list[Unknown]:
        ...
    


class _literal_bindparam(_BindParamClause):
    ...


if sqla_14:
    ...
else:
    def create_mock_engine(url, executor):
        ...
    
