[tool.poetry]
name = "ghs"
version = "2.0.0"
description = "My GitHub Stars"
authors = ["Timothy Makobu <timothy@makobu.io>"]
license = "AGPLv3"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.14.0"
starlette = "^0.15.0"
asyncpg = "^0.23.0"
httptools = "^0.2.0"
PyGithub = "^1.54.1"
newrelic = "^6.0.1"
Jinja2 = "^3.0.0"
uvloop = "^0.15.0"
requests = "^2.25.1"
hiredis = "^2.0.0"
redis = "^3.5.3"
pydantic = "^1.8.1"
cachetools = "^4.2.1"
asyncache = "^0.1.1"
types-cachetools = "^0.1.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
mypy = "^0.902"
pyflakes = "^2.2.0"
pytest-asyncio = "^0.15.0"
pytest-cov = "^2.10.1"
pytest-mock = "^3.4.0"
flake8 = "^3.8.4"
pytest-timeout = "^1.4.2"
nest-asyncio = "^1.4.3"
ipython = "^7.19.0"
jedi = "<0.18.0"
black = "^21.4b0"
pdoc3 = "^0.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
