# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('initial_stars', models.IntegerField()),
                ('current_stars', models.IntegerField(default=0)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='gitstars.Language')),
            ],
            options={
                'verbose_name_plural': 'Stars',
            },
        ),
    ]
