#!/bin/sh

# First: git config core.hooksPath `pwd`/githooks

poetry update
make test
dmypy stop
poetry export --without-hashes -f requirements.txt > requirements.txt
poetry export --dev --without-hashes -f requirements.txt > dev_requirements.txt
git add -A
