version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache

      - run:
          command: | 
            sudo pip install pipenv
            pipenv install
            pipenv install --dev
            pipenv run tox
          name: Test

  heroku_deploy:
    jobs:
      - heroku/deploy-via-git

workflows:
  build-and-deploy:
    jobs:
      - heroku_deploy
          requires:
            - test
