version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@0.2.1

workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: sequential-branch-filter

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache

      - run:
          command: | 
            sudo pip install pipenv
            pipenv install
            pipenv install --dev
            pipenv run tox
          name: Test


