version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - tests
      - heroku/deploy-via-git:
          requires:
            - tests
          filters:
            branches:
              only: master

jobs:
  tests:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          command: | 
            sudo pip install pipenv
            pipenv install
            pipenv install --dev
            pipenv run tox
          name: Tests


