# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('url', models.URLField()),
                ('initial_stars', models.IntegerField()),
                ('initial_watchers', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stars',
            },
        ),
    ]
