# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitstars', '0004_project_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='initial_watchers',
        ),
    ]
