# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstars', '0005_remove_project_initial_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
