# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstars', '0006_auto_20161018_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_stars',
            field=models.IntegerField(default=0),
        ),
    ]
