# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstars', '0007_project_current_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
