"""One-to-Many relationship fix: 2

Revision ID: 2882c3464a2d
Revises: 0dcbddb3d03c
Create Date: 2021-07-16 17:36:35.376617+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2882c3464a2d'
down_revision = '0dcbddb3d03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
