"""
This type stub file was generated by pyright.
"""

from .engine import AsyncConnectable
from .session import AsyncSession
from ...engine import events as engine_event
from ...orm import events as orm_event

class AsyncConnectionEvents(engine_event.ConnectionEvents):
    _target_class_doc = ...
    _dispatch_target = AsyncConnectable


class AsyncSessionEvents(orm_event.SessionEvents):
    _target_class_doc = ...
    _dispatch_target = AsyncSession


