"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.compiler import compiles
from .base import AddColumn, ColumnComment, ColumnDefault, ColumnName, ColumnNullable, ColumnType, IdentityColumnDefault, RenameTable
from .impl import DefaultImpl

class OracleImpl(DefaultImpl):
    __dialect__ = ...
    transactional_ddl = ...
    batch_separator = ...
    command_terminator = ...
    type_synonyms = ...
    identity_attrs_ignore = ...
    def __init__(self, *arg, **kw) -> None:
        ...
    
    def emit_begin(self): # -> None:
        ...
    
    def emit_commit(self): # -> None:
        ...
    


@compiles(AddColumn, "oracle")
def visit_add_column(element, compiler, **kw): # -> str:
    ...

@compiles(ColumnNullable, "oracle")
def visit_column_nullable(element, compiler, **kw): # -> str:
    ...

@compiles(ColumnType, "oracle")
def visit_column_type(element, compiler, **kw): # -> str:
    ...

@compiles(ColumnName, "oracle")
def visit_column_name(element, compiler, **kw): # -> str:
    ...

@compiles(ColumnDefault, "oracle")
def visit_column_default(element, compiler, **kw): # -> str:
    ...

@compiles(ColumnComment, "oracle")
def visit_column_comment(element, compiler, **kw): # -> str:
    ...

@compiles(RenameTable, "oracle")
def visit_rename_table(element, compiler, **kw): # -> str:
    ...

def alter_column(compiler, name):
    ...

def add_column(compiler, column, **kw):
    ...

@compiles(IdentityColumnDefault, "oracle")
def visit_identity_column(element, compiler, **kw): # -> str:
    ...

