"""
This type stub file was generated by pyright.
"""

from .impl import DefaultImpl

class SQLiteImpl(DefaultImpl):
    __dialect__ = ...
    transactional_ddl = ...
    def requires_recreate_in_batch(self, batch_op): # -> bool:
        """Return True if the given :class:`.BatchOperationsImpl`
        would need the table to be recreated and copied in order to
        proceed.

        Normally, only returns True on SQLite when operations other
        than add_column are present.

        """
        ...
    
    def add_constraint(self, const): # -> None:
        ...
    
    def drop_constraint(self, const): # -> None:
        ...
    
    def compare_server_default(self, inspector_column, metadata_column, rendered_metadata_default, rendered_inspector_default): # -> bool:
        ...
    
    def autogen_column_reflect(self, inspector, table, column_info): # -> None:
        ...
    
    def render_ddl_sql_expr(self, expr, is_server_default=..., **kw): # -> str:
        ...
    
    def cast_for_batch_migrate(self, existing, existing_transfer, new_type): # -> None:
        ...
    


