"""
This type stub file was generated by pyright.
"""

from .. import util

"""Provide the 'autogenerate' feature which can produce migration operations
automatically."""
def compare_metadata(context, metadata):
    """Compare a database schema to that given in a
    :class:`~sqlalchemy.schema.MetaData` instance.

    The database connection is presented in the context
    of a :class:`.MigrationContext` object, which
    provides database connectivity as well as optional
    comparison functions to use for datatypes and
    server defaults - see the "autogenerate" arguments
    at :meth:`.EnvironmentContext.configure`
    for details on these.

    The return format is a list of "diff" directives,
    each representing individual differences::

        from alembic.migration import MigrationContext
        from alembic.autogenerate import compare_metadata
        from sqlalchemy.schema import SchemaItem
        from sqlalchemy.types import TypeEngine
        from sqlalchemy import (create_engine, MetaData, Column,
                Integer, String, Table, text)
        import pprint

        engine = create_engine("sqlite://")

        with engine.begin() as conn:
            conn.execute(text('''
                create table foo (
                    id integer not null primary key,
                    old_data varchar,
                    x integer
                )'''))

            conn.execute(text('''
                create table bar (
                    data varchar
                )'''))

        metadata = MetaData()
        Table('foo', metadata,
            Column('id', Integer, primary_key=True),
            Column('data', Integer),
            Column('x', Integer, nullable=False)
        )
        Table('bat', metadata,
            Column('info', String)
        )

        mc = MigrationContext.configure(engine.connect())

        diff = compare_metadata(mc, metadata)
        pprint.pprint(diff, indent=2, width=20)

    Output::

        [ ( 'add_table',
            Table('bat', MetaData(bind=None),
                Column('info', String(), table=<bat>), schema=None)),
          ( 'remove_table',
            Table(u'bar', MetaData(bind=None),
                Column(u'data', VARCHAR(), table=<bar>), schema=None)),
          ( 'add_column',
            None,
            'foo',
            Column('data', Integer(), table=<foo>)),
          ( 'remove_column',
            None,
            'foo',
            Column(u'old_data', VARCHAR(), table=None)),
          [ ( 'modify_nullable',
              None,
              'foo',
              u'x',
              { 'existing_server_default': None,
                'existing_type': INTEGER()},
              True,
              False)]]


    :param context: a :class:`.MigrationContext`
     instance.
    :param metadata: a :class:`~sqlalchemy.schema.MetaData`
     instance.

    .. seealso::

        :func:`.produce_migrations` - produces a :class:`.MigrationScript`
        structure based on metadata comparison.

    """
    ...

def produce_migrations(context, metadata): # -> MigrationScript:
    """Produce a :class:`.MigrationScript` structure based on schema
    comparison.

    This function does essentially what :func:`.compare_metadata` does,
    but then runs the resulting list of diffs to produce the full
    :class:`.MigrationScript` object.   For an example of what this looks like,
    see the example in :ref:`customizing_revision`.

    .. seealso::

        :func:`.compare_metadata` - returns more fundamental "diff"
        data from comparing a schema.

    """
    ...

def render_python_code(up_or_down_op, sqlalchemy_module_prefix=..., alembic_module_prefix=..., render_as_batch=..., imports=..., render_item=..., migration_context=...): # -> str:
    """Render Python code given an :class:`.UpgradeOps` or
    :class:`.DowngradeOps` object.

    This is a convenience function that can be used to test the
    autogenerate output of a user-defined :class:`.MigrationScript` structure.

    """
    ...

class AutogenContext:
    """Maintains configuration and state that's specific to an
    autogenerate operation."""
    metadata = ...
    connection = ...
    dialect = ...
    imports = ...
    migration_context = ...
    def __init__(self, migration_context, metadata=..., opts=..., autogenerate=...) -> None:
        ...
    
    @util.memoized_property
    def inspector(self):
        ...
    
    def run_name_filters(self, name, type_, parent_names): # -> bool:
        """Run the context's name filters and return True if the targets
        should be part of the autogenerate operation.

        This method should be run for every kind of name encountered within the
        reflection side of an autogenerate operation, giving the environment
        the chance to filter what names should be reflected as database
        objects.  The filters here are produced directly via the
        :paramref:`.EnvironmentContext.configure.include_name` parameter.

        """
        ...
    
    def run_object_filters(self, object_, name, type_, reflected, compare_to): # -> bool:
        """Run the context's object filters and return True if the targets
        should be part of the autogenerate operation.

        This method should be run for every kind of object encountered within
        an autogenerate operation, giving the environment the chance
        to filter what objects should be included in the comparison.
        The filters here are produced directly via the
        :paramref:`.EnvironmentContext.configure.include_object` parameter.

        """
        ...
    
    run_filters = ...
    @util.memoized_property
    def sorted_tables(self): # -> list[Unknown]:
        """Return an aggregate of the :attr:`.MetaData.sorted_tables` collection(s).

        For a sequence of :class:`.MetaData` objects, this
        concatenates the :attr:`.MetaData.sorted_tables` collection
        for each individual :class:`.MetaData`  in the order of the
        sequence.  It does **not** collate the sorted tables collections.

        """
        ...
    
    @util.memoized_property
    def table_key_to_table(self): # -> dict[Unknown, Unknown]:
        """Return an aggregate  of the :attr:`.MetaData.tables` dictionaries.

        The :attr:`.MetaData.tables` collection is a dictionary of table key
        to :class:`.Table`; this method aggregates the dictionary across
        multiple :class:`.MetaData` objects into one dictionary.

        Duplicate table keys are **not** supported; if two :class:`.MetaData`
        objects contain the same table key, an exception is raised.

        """
        ...
    


class RevisionContext:
    """Maintains configuration and state that's specific to a revision
    file generation operation."""
    def __init__(self, config, script_directory, command_args, process_revision_directives=...) -> None:
        ...
    
    def run_autogenerate(self, rev, migration_context): # -> None:
        ...
    
    def run_no_autogenerate(self, rev, migration_context): # -> None:
        ...
    
    def generate_scripts(self): # -> Generator[Unknown, None, None]:
        ...
    


