"""
This type stub file was generated by pyright.
"""

from .api import CANCEL, NO_RETVAL, contains, listen, listens_for, remove
from .attr import RefCollection
from .base import Events, dispatcher
from .legacy import _legacy_signature

