# Generated by Django 3.0.8 on 2020-07-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('initial_stars', models.IntegerField()),
                ('current_stars', models.IntegerField(default=0)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='stars.ProgrammingLanguage')),
            ],
            options={
                'verbose_name_plural': 'Stars',
            },
        ),
        migrations.AddIndex(
            model_name='programminglanguage',
            index=models.Index(fields=['name'], name='stars_progr_name_95f3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name', 'full_name', 'description'], name='stars_proje_name_c5f214_idx'),
        ),
    ]
