name: GHS

on:
  push:
    branches: [2.0]
  pull_request:
    branches: [2.0]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        python-version: [3.9.5]

    steps:
      - uses: actions/checkout@v2
        with:
          # https://github.com/actions/checkout/issues/217#issuecomment-634802933
          fetch-depth: "0"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('dev_requirements.txt') }}

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -r dev_requirements.txt

      - name: Run Tests
        run: |
          pytest

      ### Deploy to Heroku ###
      - name: Add Heroku remote
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy
        # First run (once): $ heroku stack:set container -a app_name
        run: |
          git push -f heroku HEAD:master
