name: ghs

on:
  push:
    branches: [ 2.0 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        python-version: [3.9.1]

    steps:
    - uses: actions/checkout@v2
      with:
        # https://github.com/actions/checkout/issues/217#issuecomment-634802933
        fetch-depth: "0"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install poetry tox

    - name: Run Tests
      run: |
        tox
      env:
        GHA: "1"
